// T&C contratto noleggio + labels UI — 5 lingue

const CONTRATTO_TERMS = {
  it: [
    { title: `Art. 1 — Oggetto e Parti`, text: `Il presente contratto regola il noleggio di una bicicletta elettrica da parte di Arfanta Bike Rental (di seguito "Noleggiatore"), con sede in Via Pecol 22, Arfanta di Tarzo (TV), email: arfantabikerental@gmail.com, nei confronti del cliente (di seguito "Conduttore").` },
    { title: `Art. 2 — Requisiti del Conduttore`, text: `Il Conduttore dichiara di avere almeno 18 anni di età, di essere fisicamente idoneo alla guida di una bicicletta elettrica e di non essere sotto l'effetto di alcol, droghe o farmaci che possano alterare la capacità di guida. Al momento del ritiro dovrà esibire un documento d'identità valido.` },
    { title: `Art. 3 — Uso del Veicolo`, text: `La bicicletta è consegnata in perfetto stato di manutenzione. Il Conduttore si impegna a: (a) utilizzarla esclusivamente per uso personale e ricreativo su strade e percorsi idonei; (b) rispettare il Codice della Strada e le norme locali; (c) non partecipare a gare, competizioni o prove cronometrate; (d) non subaffittare il mezzo a terzi; (e) non apportare modifiche ai componenti della bicicletta; (f) non trasportare passeggeri se non espressamente previsto dal modello; (g) indossare il casco (vivamente consigliato). È vietato l'uso fuori strada (off-road) non concordato con il Noleggiatore.` },
    { title: `Art. 4 — Ritiro e Restituzione`, text: `La bicicletta deve essere ritirata e restituita negli orari concordati in sede. Per ritardi nella restituzione superiori a 30 minuti, il Noleggiatore si riserva il diritto di addebitare €10 per ogni ora o frazione di ora aggiuntiva. La bicicletta va restituita nello stesso stato in cui è stata consegnata: pulita, funzionante e con la batteria non completamente scarica.` },
    { title: `Art. 5 — Responsabilità per Danni e Furto`, text: `Il Conduttore è responsabile di qualsiasi danno alla bicicletta (ammaccature, rotture, graffi profondi) causato per negligenza, uso improprio o incidente durante il periodo di noleggio, indipendentemente dall'autore del sinistro. In caso di furto, il Conduttore è responsabile per il valore integrale del mezzo. Una cauzione di €500 viene pre-autorizzata sulla carta di credito al momento del ritiro e sbloccata alla restituzione senza danni. L'usura fisiologica derivante dal normale utilizzo non è addebitata.` },
    { title: `Art. 6 — Esclusioni di Responsabilità`, text: `Il Noleggiatore declina ogni responsabilità per: (a) danni a terzi o a cose causati dal Conduttore durante il noleggio; (b) infortuni fisici subiti dal Conduttore durante l'utilizzo del mezzo; (c) guasti meccanici dovuti ad uso improprio o negligenza. Il Conduttore è invitato a verificare la propria copertura assicurativa personale. La bicicletta è dotata di assistenza di primo livello (kit foratura disponibile su richiesta).` },
    { title: `Art. 7 — Cancellazione e Rimborso`, text: `Cancellazioni comunicate oltre 48 ore prima dell'inizio del noleggio: rimborso integrale dell'importo pagato. Cancellazioni entro 48 ore dall'inizio: nessun rimborso, salvo forza maggiore documentata (es. ricovero ospedaliero, grave lutto familiare), valutata individualmente dal Noleggiatore. Condizioni meteorologiche avverse non danno diritto a rimborso automatico.` },
    { title: `Art. 8 — Trattamento dei Dati Personali (GDPR)`, text: `Ai sensi del Regolamento UE 2016/679 (GDPR) e del D.lgs. 196/2003, i dati personali del Conduttore (nome, cognome, email, telefono, dati di prenotazione) sono trattati da Arfanta Bike Rental in qualità di Titolare del trattamento per le seguenti finalità: (a) esecuzione del contratto di noleggio; (b) invio di comunicazioni relative alla prenotazione; (c) adempimento di obblighi legali e fiscali. I dati non sono ceduti a terzi, ad eccezione dei soggetti strettamente necessari all'erogazione del servizio (es. gestore pagamenti Stripe). Sono conservati per un periodo massimo di 5 anni dalla data della prenotazione, dopodiché vengono cancellati in modo sicuro. Il Conduttore ha diritto di accedere, rettificare, cancellare i propri dati, opporsi al trattamento, richiederne la portabilità e revocare il consenso in qualsiasi momento, scrivendo a arfantabikerental@gmail.com.` },
    { title: `Art. 9 — Legge Applicabile e Foro Competente`, text: `Il presente contratto è regolato dalla legge italiana. Per qualsiasi controversia derivante dal presente contratto, le parti concordano la competenza esclusiva del Tribunale di Treviso.` },
  ],

  en: [
    { title: `Art. 1 — Subject and Parties`, text: `This agreement governs the rental of an electric bicycle by Arfanta Bike Rental (hereinafter "Lessor"), located at Via Pecol 22, Arfanta di Tarzo (TV), Italy, email: arfantabikerental@gmail.com, to the customer (hereinafter "Renter").` },
    { title: `Art. 2 — Requirements`, text: `The Renter declares to be at least 18 years of age, physically fit to ride an electric bicycle, and not under the influence of alcohol, drugs or medications that may impair riding ability. A valid identity document must be presented at the time of pickup.` },
    { title: `Art. 3 — Use of the Bicycle`, text: `The bicycle is provided in perfect working condition. The Renter agrees to: (a) use it solely for personal and recreational purposes on suitable roads and paths; (b) comply with the Italian Highway Code and local regulations; (c) not participate in any race, competition or timed event; (d) not sublet the bicycle to third parties; (e) not modify any bicycle components; (f) not carry passengers unless the model expressly permits it; (g) wear a helmet (strongly recommended). Off-road use must be agreed in advance with the Lessor.` },
    { title: `Art. 4 — Pickup and Return`, text: `The bicycle must be picked up and returned at the agreed times and location. For returns more than 30 minutes late, the Lessor reserves the right to charge €10 per additional hour or fraction thereof. The bicycle must be returned in the same condition as delivered: clean, functioning, and not with a completely discharged battery.` },
    { title: `Art. 5 — Liability for Damage and Theft`, text: `The Renter is liable for any damage to the bicycle (dents, breakages, deep scratches) caused by negligence, improper use, or accident during the rental period, regardless of who caused the incident. In the event of theft, the Renter is liable for the full replacement value of the bicycle. A €500 security deposit is pre-authorized on the credit card at pickup and released upon undamaged return. Normal wear and tear from ordinary use is not charged.` },
    { title: `Art. 6 — Limitation of Liability`, text: `The Lessor accepts no liability for: (a) damage to third parties or property caused by the Renter during the rental; (b) personal injuries sustained by the Renter during use; (c) mechanical failures due to improper use or negligence. The Renter is advised to verify their personal insurance coverage.` },
    { title: `Art. 7 — Cancellation and Refund`, text: `Cancellations made more than 48 hours before the start of the rental: full refund. Cancellations within 48 hours of the start: no refund, unless force majeure is documented (e.g. hospitalisation, bereavement), assessed individually by the Lessor. Adverse weather conditions do not entitle the Renter to an automatic refund.` },
    { title: `Art. 8 — Personal Data Processing (GDPR)`, text: `Pursuant to EU Regulation 2016/679 (GDPR), the Renter's personal data (name, email, telephone, booking details) are processed by Arfanta Bike Rental as Data Controller for the following purposes: (a) performance of the rental agreement; (b) sending booking-related communications; (c) fulfilment of legal and fiscal obligations. Data are not shared with third parties, except those strictly necessary for service delivery (e.g. Stripe payment processor). Data are retained for a maximum of 5 years from the booking date, after which they are securely deleted. The Renter has the right to access, rectify, delete, object to processing, request portability and withdraw consent at any time by writing to arfantabikerental@gmail.com.` },
    { title: `Art. 9 — Governing Law and Jurisdiction`, text: `This agreement is governed by Italian law. For any dispute arising from this agreement, the parties agree on the exclusive jurisdiction of the Court of Treviso, Italy.` },
  ],

  de: [
    { title: `Art. 1 — Gegenstand und Parteien`, text: `Dieser Vertrag regelt die Vermietung eines Elektrofahrrads durch Arfanta Bike Rental (im Folgenden "Vermieter"), mit Sitz in Via Pecol 22, Arfanta di Tarzo (TV), Italien, E-Mail: arfantabikerental@gmail.com, an den Kunden (im Folgenden "Mieter").` },
    { title: `Art. 2 — Anforderungen`, text: `Der Mieter erklärt, mindestens 18 Jahre alt zu sein, körperlich in der Lage zu sein, ein Elektrofahrrad zu fahren, und nicht unter dem Einfluss von Alkohol, Drogen oder Medikamenten zu stehen, die die Fahrtüchtigkeit beeinträchtigen könnten. Bei der Abholung ist ein gültiger Personalausweis vorzulegen.` },
    { title: `Art. 3 — Nutzung des Fahrrads`, text: `Das Fahrrad wird in einwandfreiem Zustand übergeben. Der Mieter verpflichtet sich: (a) es ausschließlich für den persönlichen Freizeitgebrauch auf geeigneten Straßen und Wegen zu nutzen; (b) die Straßenverkehrsordnung und lokale Vorschriften einzuhalten; (c) nicht an Rennen, Wettkämpfen oder Zeitfahrten teilzunehmen; (d) das Fahrrad nicht unterzuvermieten; (e) keine Änderungen an den Fahrradkomponenten vorzunehmen; (f) keinen Beifahrer zu befördern, sofern das Modell dies nicht ausdrücklich erlaubt; (g) einen Helm zu tragen (dringend empfohlen). Geländefahrten (Offroad) müssen im Voraus mit dem Vermieter abgestimmt werden.` },
    { title: `Art. 4 — Abholung und Rückgabe`, text: `Das Fahrrad muss zu den vereinbarten Zeiten abgeholt und zurückgegeben werden. Bei Rückgabe von mehr als 30 Minuten Verspätung behält sich der Vermieter das Recht vor, €10 pro angefangene Stunde in Rechnung zu stellen. Das Fahrrad ist in demselben Zustand zurückzugeben, in dem es übergeben wurde: sauber, funktionsfähig und nicht mit vollständig entladener Batterie.` },
    { title: `Art. 5 — Haftung für Schäden und Diebstahl`, text: `Der Mieter haftet für alle Schäden am Fahrrad (Dellen, Brüche, tiefe Kratzer), die durch Fahrlässigkeit, unsachgemäßen Gebrauch oder einen Unfall während der Mietzeit verursacht wurden, unabhängig davon, wer den Schaden verursacht hat. Im Falle eines Diebstahls haftet der Mieter für den vollen Wiederbeschaffungswert des Fahrrads. Eine Kaution von €500 wird bei der Abholung auf der Kreditkarte vorautorisiert und nach unbeschädigter Rückgabe freigegeben. Normaler Verschleiß durch übliche Nutzung wird nicht in Rechnung gestellt.` },
    { title: `Art. 6 — Haftungsausschluss`, text: `Der Vermieter übernimmt keine Haftung für: (a) Schäden an Dritten oder Sachen, die durch den Mieter während der Mietzeit verursacht werden; (b) körperliche Verletzungen des Mieters bei der Nutzung des Fahrrads; (c) mechanische Störungen aufgrund unsachgemäßer Nutzung oder Fahrlässigkeit. Der Mieter wird empfohlen, seinen persönlichen Versicherungsschutz zu überprüfen.` },
    { title: `Art. 7 — Stornierung und Erstattung`, text: `Stornierungen, die mehr als 48 Stunden vor Beginn der Miete mitgeteilt werden: vollständige Rückerstattung. Stornierungen innerhalb von 48 Stunden vor Beginn: keine Rückerstattung, es sei denn, es liegt ein nachgewiesener Fall höherer Gewalt vor (z.B. Krankenhausaufenthalt, schwerer Trauerfall), der individuell vom Vermieter bewertet wird. Ungünstige Wetterbedingungen berechtigen nicht zu einer automatischen Rückerstattung.` },
    { title: `Art. 8 — Datenschutz (DSGVO)`, text: `Gemäß der EU-Verordnung 2016/679 (DSGVO) werden die personenbezogenen Daten des Mieters (Name, E-Mail, Telefon, Buchungsdaten) von Arfanta Bike Rental als Verantwortlichem für folgende Zwecke verarbeitet: (a) Erfüllung des Mietvertrags; (b) Zusendung buchungsbezogener Mitteilungen; (c) Erfüllung rechtlicher und steuerlicher Pflichten. Die Daten werden nicht an Dritte weitergegeben, außer an jene, die zur Erbringung des Dienstes unbedingt erforderlich sind (z.B. Stripe für die Zahlungsabwicklung). Die Daten werden maximal 5 Jahre ab dem Buchungsdatum aufbewahrt und anschließend sicher gelöscht. Der Mieter hat das Recht auf Auskunft, Berichtigung, Löschung, Widerspruch, Datenübertragbarkeit und Widerruf der Einwilligung durch Schreiben an arfantabikerental@gmail.com.` },
    { title: `Art. 9 — Anwendbares Recht und Gerichtsstand`, text: `Dieser Vertrag unterliegt italienischem Recht. Für etwaige Streitigkeiten aus diesem Vertrag vereinbaren die Parteien die ausschließliche Zuständigkeit des Gerichts Treviso, Italien.` },
  ],

  es: [
    { title: `Art. 1 — Objeto y Partes`, text: `El presente contrato regula el alquiler de una bicicleta eléctrica por parte de Arfanta Bike Rental (en adelante "Arrendador"), con sede en Via Pecol 22, Arfanta di Tarzo (TV), Italia, email: arfantabikerental@gmail.com, al cliente (en adelante "Arrendatario").` },
    { title: `Art. 2 — Requisitos`, text: `El Arrendatario declara tener al menos 18 años de edad, estar físicamente capacitado para conducir una bicicleta eléctrica y no estar bajo los efectos del alcohol, drogas o medicamentos que puedan afectar la capacidad de conducción. Deberá presentar un documento de identidad válido en el momento de la recogida.` },
    { title: `Art. 3 — Uso de la Bicicleta`, text: `La bicicleta se entrega en perfecto estado de mantenimiento. El Arrendatario se compromete a: (a) utilizarla exclusivamente para uso personal y recreativo en carreteras y caminos adecuados; (b) respetar el Código de Circulación y las normativas locales; (c) no participar en carreras, competiciones ni pruebas cronometradas; (d) no subarrendar el vehículo; (e) no realizar modificaciones en los componentes; (f) no transportar pasajeros salvo que el modelo lo permita expresamente; (g) llevar casco (muy recomendado). El uso fuera de carretera debe acordarse previamente con el Arrendador.` },
    { title: `Art. 4 — Recogida y Devolución`, text: `La bicicleta debe recogerse y devolverse en los horarios acordados. Por retrasos en la devolución superiores a 30 minutos, el Arrendador se reserva el derecho de cobrar €10 por cada hora adicional o fracción. La bicicleta debe devolverse en el mismo estado en que fue entregada: limpia, en funcionamiento y sin la batería completamente descargada.` },
    { title: `Art. 5 — Responsabilidad por Daños y Robo`, text: `El Arrendatario es responsable de cualquier daño a la bicicleta (abolladuras, roturas, arañazos profundos) causado por negligencia, uso indebido o accidente durante el período de alquiler, independientemente de quién haya causado el incidente. En caso de robo, el Arrendatario es responsable del valor íntegro del vehículo. Una fianza de €500 se preautoriza en la tarjeta de crédito al recoger y se libera al devolver sin daños. El desgaste normal por uso ordinario no se factura.` },
    { title: `Art. 6 — Limitación de Responsabilidad`, text: `El Arrendador declina toda responsabilidad por: (a) daños a terceros o a bienes causados por el Arrendatario durante el alquiler; (b) lesiones físicas sufridas por el Arrendatario durante el uso; (c) averías mecánicas debidas a uso indebido o negligencia. Se recomienda al Arrendatario verificar su cobertura de seguro personal.` },
    { title: `Art. 7 — Cancelación y Reembolso`, text: `Cancelaciones comunicadas con más de 48 horas de antelación: reembolso íntegro. Cancelaciones dentro de las 48 horas previas: sin reembolso, salvo fuerza mayor debidamente documentada (p. ej. hospitalización, duelo grave), evaluada individualmente por el Arrendador. Las condiciones meteorológicas adversas no dan derecho a un reembolso automático.` },
    { title: `Art. 8 — Protección de Datos (RGPD)`, text: `De conformidad con el Reglamento UE 2016/679 (RGPD), los datos personales del Arrendatario (nombre, email, teléfono, datos de reserva) son tratados por Arfanta Bike Rental como Responsable del tratamiento con las siguientes finalidades: (a) ejecución del contrato de alquiler; (b) envío de comunicaciones relacionadas con la reserva; (c) cumplimiento de obligaciones legales y fiscales. Los datos no se ceden a terceros, salvo los estrictamente necesarios para la prestación del servicio (p. ej. Stripe para el pago). Se conservan un máximo de 5 años desde la fecha de reserva, tras los cuales se eliminan de forma segura. El Arrendatario tiene derecho a acceder, rectificar, suprimir, oponerse al tratamiento, solicitar la portabilidad y revocar el consentimiento en cualquier momento escribiendo a arfantabikerental@gmail.com.` },
    { title: `Art. 9 — Ley Aplicable y Jurisdicción`, text: `El presente contrato se rige por la legislación italiana. Para cualquier controversia derivada de este contrato, las partes acuerdan la competencia exclusiva del Tribunal de Treviso, Italia.` },
  ],

  fr: [
    { title: `Art. 1 — Objet et Parties`, text: `Le présent contrat régit la location d'un vélo électrique par Arfanta Bike Rental (ci-après « Loueur »), dont le siège est Via Pecol 22, Arfanta di Tarzo (TV), Italie, email : arfantabikerental@gmail.com, au profit du client (ci-après « Locataire »).` },
    { title: `Art. 2 — Conditions requises`, text: `Le Locataire déclare avoir au moins 18 ans, être physiquement apte à conduire un vélo électrique et ne pas être sous l'influence de l'alcool, de drogues ou de médicaments susceptibles d'altérer ses capacités de conduite. Une pièce d'identité valide devra être présentée au moment de la prise en charge.` },
    { title: `Art. 3 — Utilisation du Vélo`, text: `Le vélo est remis en parfait état de fonctionnement. Le Locataire s'engage à : (a) l'utiliser exclusivement à des fins personnelles et récréatives sur des routes et chemins appropriés ; (b) respecter le Code de la route et les réglementations locales ; (c) ne pas participer à des courses, compétitions ou épreuves chronométrées ; (d) ne pas sous-louer le vélo à des tiers ; (e) ne pas modifier les composants du vélo ; (f) ne pas transporter de passagers sauf si le modèle le permet expressément ; (g) porter un casque (fortement recommandé). L'utilisation hors route doit être convenue à l'avance avec le Loueur.` },
    { title: `Art. 4 — Prise en Charge et Restitution`, text: `Le vélo doit être pris en charge et restitué aux horaires convenus. Pour tout retard de restitution supérieur à 30 minutes, le Loueur se réserve le droit de facturer €10 par heure supplémentaire ou fraction d'heure. Le vélo doit être restitué dans le même état qu'au moment de la remise : propre, en état de marche et avec une batterie non complètement déchargée.` },
    { title: `Art. 5 — Responsabilité pour Dommages et Vol`, text: `Le Locataire est responsable de tout dommage au vélo (bosses, casses, griffures profondes) causé par négligence, mauvais usage ou accident pendant la période de location, quel que soit l'auteur du sinistre. En cas de vol, le Locataire est responsable de la valeur intégrale du vélo. Une caution de €500 est pré-autorisée sur la carte de crédit lors de la prise en charge et débloquée à la restitution sans dommage. L'usure normale due à une utilisation ordinaire n'est pas facturée.` },
    { title: `Art. 6 — Limitation de Responsabilité`, text: `Le Loueur décline toute responsabilité pour : (a) les dommages causés à des tiers ou à des biens par le Locataire pendant la location ; (b) les blessures physiques subies par le Locataire lors de l'utilisation du vélo ; (c) les pannes mécaniques dues à un mauvais usage ou à la négligence. Il est conseillé au Locataire de vérifier sa couverture d'assurance personnelle.` },
    { title: `Art. 7 — Annulation et Remboursement`, text: `Annulations effectuées plus de 48 heures avant le début de la location : remboursement intégral. Annulations dans les 48 heures précédant la location : aucun remboursement, sauf cas de force majeure dûment documenté (ex. hospitalisation, deuil grave), apprécié individuellement par le Loueur. Les mauvaises conditions météorologiques n'ouvrent pas droit à un remboursement automatique.` },
    { title: `Art. 8 — Protection des Données (RGPD)`, text: `Conformément au Règlement UE 2016/679 (RGPD), les données personnelles du Locataire (nom, email, téléphone, données de réservation) sont traitées par Arfanta Bike Rental en qualité de Responsable du traitement aux fins suivantes : (a) exécution du contrat de location ; (b) envoi de communications relatives à la réservation ; (c) respect des obligations légales et fiscales. Les données ne sont pas transmises à des tiers, sauf à ceux strictement nécessaires à la prestation du service (ex. Stripe pour les paiements). Elles sont conservées pendant 5 ans maximum à compter de la date de réservation, puis supprimées de manière sécurisée. Le Locataire dispose des droits d'accès, de rectification, d'effacement, d'opposition, de portabilité et de retrait du consentement à tout moment en écrivant à arfantabikerental@gmail.com.` },
    { title: `Art. 9 — Droit Applicable et Juridiction`, text: `Le présent contrat est régi par le droit italien. Pour tout litige découlant de ce contrat, les parties conviennent de la compétence exclusive du Tribunal de Trévise, Italie.` },
  ],
};

const TIPO_LABEL = {
  it: { mezza_mattina: 'Mezza Giornata Mattina (09:00–13:00)', mezza_pomeriggio: 'Mezza Giornata Pomeriggio (14:00–18:00)', intera_giornata: 'Giornata Intera (09:00–18:00)', multi_giorno: 'Multi-Giorno' },
  en: { mezza_mattina: 'Half Day Morning (09:00–13:00)', mezza_pomeriggio: 'Half Day Afternoon (14:00–18:00)', intera_giornata: 'Full Day (09:00–18:00)', multi_giorno: 'Multi-Day' },
  de: { mezza_mattina: 'Halbtag Vormittag (09:00–13:00)', mezza_pomeriggio: 'Halbtag Nachmittag (14:00–18:00)', intera_giornata: 'Ganztag (09:00–18:00)', multi_giorno: 'Mehrtägig' },
  es: { mezza_mattina: 'Medio Día Mañana (09:00–13:00)', mezza_pomeriggio: 'Medio Día Tarde (14:00–18:00)', intera_giornata: 'Día Completo (09:00–18:00)', multi_giorno: 'Varios Días' },
  fr: { mezza_mattina: 'Demi-Journée Matin (09h00–13h00)', mezza_pomeriggio: 'Demi-Journée Après-midi (14h00–18h00)', intera_giornata: 'Journée Complète (09h00–18h00)', multi_giorno: 'Plusieurs Jours' },
};

const CONTRATTO_TITLE = {
  it: 'Contratto di Noleggio', en: 'Rental Agreement',
  de: 'Mietvertrag',          es: 'Contrato de Alquiler', fr: 'Contrat de Location',
};

const CONTRATTO_FIELDS = {
  it: { summary: 'Riepilogo Prenotazione', code: 'Codice prenotazione', client: 'Cliente', type: 'Tipo noleggio', pickup: 'Ritiro', ret: 'Restituzione', price: 'Importo pagato', terms: 'Termini e Condizioni', cert: 'Certificato di Firma Digitale', docid: 'ID Documento', signer: 'Firmato da', date: 'Data e ora firma (CET)', ip: 'Indirizzo IP', booking: 'Codice prenotazione', footer: 'Documento generato automaticamente da Arfanta Bike Rental. Questo documento ha valore legale ai fini della verifica del consenso contrattuale.', print: 'Stampa / Salva PDF' },
  en: { summary: 'Booking Summary', code: 'Booking code', client: 'Customer', type: 'Rental type', pickup: 'Pickup', ret: 'Return', price: 'Amount paid', terms: 'Terms & Conditions', cert: 'Digital Signature Certificate', docid: 'Document ID', signer: 'Signed by', date: 'Date and time (CET)', ip: 'IP Address', booking: 'Booking code', footer: 'Automatically generated by Arfanta Bike Rental. This document serves as legal proof of contractual consent.', print: 'Print / Save PDF' },
  de: { summary: 'Buchungsübersicht', code: 'Buchungscode', client: 'Kunde', type: 'Mietart', pickup: 'Abholung', ret: 'Rückgabe', price: 'Bezahlter Betrag', terms: 'AGB', cert: 'Digitales Signaturzertifikat', docid: 'Dokument-ID', signer: 'Unterzeichnet von', date: 'Datum und Uhrzeit (MEZ)', ip: 'IP-Adresse', booking: 'Buchungscode', footer: 'Automatisch von Arfanta Bike Rental generiert. Dieses Dokument dient als Nachweis der Vertragsannahme.', print: 'Drucken / Als PDF speichern' },
  es: { summary: 'Resumen de la Reserva', code: 'Código de reserva', client: 'Cliente', type: 'Tipo', pickup: 'Recogida', ret: 'Devolución', price: 'Importe pagado', terms: 'Términos y Condiciones', cert: 'Certificado de Firma Digital', docid: 'ID Documento', signer: 'Firmado por', date: 'Fecha y hora (CET)', ip: 'Dirección IP', booking: 'Código de reserva', footer: 'Generado automáticamente por Arfanta Bike Rental. Este documento sirve como prueba legal del consentimiento contractual.', print: 'Imprimir / Guardar PDF' },
  fr: { summary: 'Récapitulatif de Réservation', code: 'Code de réservation', client: 'Client', type: 'Type de location', pickup: 'Prise en charge', ret: 'Retour', price: 'Montant payé', terms: 'Conditions Générales', cert: 'Certificat de Signature Numérique', docid: 'ID Document', signer: 'Signé par', date: 'Date et heure (CET)', ip: 'Adresse IP', booking: 'Code de réservation', footer: 'Généré automatiquement par Arfanta Bike Rental. Ce document atteste du consentement contractuel.', print: 'Imprimer / Enregistrer en PDF' },
};

const LOCALE_MAP = { it: 'it-IT', en: 'en-GB', de: 'de-DE', es: 'es-ES', fr: 'fr-FR' };

module.exports = { CONTRATTO_TERMS, TIPO_LABEL, CONTRATTO_TITLE, CONTRATTO_FIELDS, LOCALE_MAP };
